version: '3'
services:
        web:
                build: .
                ports:
                        - "4096:4096"
                        - "5000:5000"
                restart: always
                volumes:
                        - /:/mnt/host
        redis:
                image: "redis:alpine"
